# Generated by Django 2.2.12 on 2023-04-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endowment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fond_jobosu', models.FilePathField(path='fondjobosu/', verbose_name='Фонддун жобосу')),
                ('student_list', models.FilePathField(path='studentlist/', verbose_name='Бутуруучулордун тизмеси')),
            ],
            options={
                'verbose_name': 'Эндаумент',
                'verbose_name_plural': 'Эндаументы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='ФИО ученика')),
                ('image', models.ImageField(upload_to='students/')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='ФИО учителя')),
                ('biography', models.CharField(max_length=50, verbose_name='Биография')),
                ('image', models.ImageField(upload_to='teachers/')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
    ]
