# Generated by Django 2.2.12 on 2023-04-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endowment',
            name='fond_jobosu',
            field=models.FileField(upload_to='fondjobosu/', verbose_name='Фонддун жобосу'),
        ),
        migrations.AlterField(
            model_name='endowment',
            name='student_list',
            field=models.FileField(upload_to='studentslist/', verbose_name='Бутуруучулордун тизмеси'),
        ),
    ]
