# Generated by Django 2.2.12 on 2023-04-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230422_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='Жылы(год)')),
                ('ustav', models.FileField(upload_to='documents/ustav/', verbose_name='Устав')),
                ('protocol', models.FileField(upload_to='documents/protocol/', verbose_name='Протокол')),
                ('jobo', models.FileField(upload_to='documents/jobo/', verbose_name='Жобо')),
                ('plan', models.FileField(upload_to='documents/plan/', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Аккредитация',
                'verbose_name_plural': 'Аккредитация',
            },
        ),
        migrations.CreateModel(
            name='MediaTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50, verbose_name='Тема мероприятия')),
            ],
            options={
                'verbose_name': 'Темы Событий',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='birikme',
            field=models.CharField(choices=[(1, 'Табигый илимдер'), (2, 'Кыргыз тили'), (3, 'Орус тили'), (4, 'Англис тили'), (5, 'Физика'), (6, 'Математика'), (7, 'Технология')], default=1, max_length=30, verbose_name='Усулдук Бирикме'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Фото')),
                ('video', models.URLField(blank=True, verbose_name='Видео (ссылка)')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycontent', to='main.MediaTheme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тема События',
                'verbose_name_plural': 'Темы Событий',
            },
        ),
    ]
