# Generated by Django 2.2.12 on 2023-04-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230423_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='desc',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='video',
            field=models.URLField(blank=True, help_text='Cсылка на видео', verbose_name='Видео'),
        ),
    ]
