# Generated by Django 2.2.12 on 2023-04-24 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230423_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Окуучу', 'verbose_name_plural': 'Окуучулар'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Мугалим', 'verbose_name_plural': 'Мугалимдер'},
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='jobo',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='ustav',
        ),
        migrations.CreateModel(
            name='Ustav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('ustav', models.FileField(upload_to='documents/ustav/', verbose_name='Устав')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ustavtar', to='main.Accreditation', verbose_name='Жылы(год)')),
            ],
            options={
                'verbose_name': 'Устав',
                'verbose_name_plural': 'Уставтар',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('protocol', models.FileField(upload_to='documents/protocol/', verbose_name='Протокол')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='main.Accreditation', verbose_name='Жылы(год)')),
            ],
            options={
                'verbose_name': 'Протокол',
                'verbose_name_plural': 'Протоколдор',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('plan', models.FileField(upload_to='documents/plan/', verbose_name='План')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='main.Accreditation', verbose_name='Жылы(год)')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Пландар',
            },
        ),
        migrations.CreateModel(
            name='Jobo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('jobo', models.FileField(upload_to='documents/jobo/', verbose_name='Жобо')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobolor', to='main.Accreditation', verbose_name='Жылы(год)')),
            ],
            options={
                'verbose_name': 'Жобо',
                'verbose_name_plural': 'Жоболор',
            },
        ),
    ]
